
petclinic: 
       image: sannakko/petclinic:latest
       ports:
          - "9999:8080"

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=test
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"
